// NourishLog Food Database — 500+ Indian dishes with accurate nutrition data
// cal=calories, p=protein(g), c=carbs(g), f=fat(g), fb=fiber(g), score=health score(1-10)

type FoodData = { cal: number; p: number; c: number; f: number; fb: number; score: number; category: string; aliases?: string[] };

export const foodDatabase: Record<string, FoodData> = {
  // ══════════════════════════════════════════════
  // SOUTH INDIAN — Breakfast & Mains
  // ══════════════════════════════════════════════
  'dosa': { cal: 120, p: 3, c: 18, f: 4, fb: 1, score: 7, category: 'breakfast', aliases: ['plain dosa', 'sada dosa'] },
  'masala dosa': { cal: 166, p: 4, c: 24, f: 7, fb: 2, score: 7, category: 'breakfast' },
  'rava dosa': { cal: 180, p: 4, c: 28, f: 6, fb: 1, score: 6, category: 'breakfast', aliases: ['sooji dosa'] },
  'onion dosa': { cal: 150, p: 4, c: 22, f: 5, fb: 1, score: 7, category: 'breakfast' },
  'paper dosa': { cal: 130, p: 3, c: 20, f: 4, fb: 1, score: 7, category: 'breakfast', aliases: ['paper roast'] },
  'mysore dosa': { cal: 190, p: 4, c: 26, f: 8, fb: 2, score: 6, category: 'breakfast' },
  'set dosa': { cal: 170, p: 4, c: 28, f: 5, fb: 2, score: 7, category: 'breakfast' },
  'neer dosa': { cal: 130, p: 2, c: 22, f: 3, fb: 1, score: 8, category: 'breakfast' },
  'pesarattu': { cal: 200, p: 10, c: 28, f: 5, fb: 4, score: 8, category: 'breakfast', aliases: ['moong dosa'] },
  'ghee roast dosa': { cal: 220, p: 4, c: 26, f: 12, fb: 1, score: 5, category: 'breakfast' },
  'egg dosa': { cal: 190, p: 10, c: 20, f: 8, fb: 1, score: 7, category: 'breakfast' },
  'cheese dosa': { cal: 240, p: 8, c: 22, f: 14, fb: 1, score: 5, category: 'breakfast' },
  'idli': { cal: 39, p: 2, c: 8, f: 0, fb: 1, score: 9, category: 'breakfast', aliases: ['plain idli'] },
  'idli sambar': { cal: 150, p: 5, c: 28, f: 2, fb: 3, score: 8, category: 'breakfast' },
  'rava idli': { cal: 55, p: 2, c: 10, f: 1, fb: 1, score: 7, category: 'breakfast' },
  'mini idli': { cal: 140, p: 4, c: 26, f: 2, fb: 2, score: 8, category: 'breakfast', aliases: ['button idli'] },
  'kanchipuram idli': { cal: 70, p: 2, c: 12, f: 2, fb: 1, score: 7, category: 'breakfast' },
  'uttapam': { cal: 150, p: 4, c: 22, f: 5, fb: 2, score: 7, category: 'breakfast', aliases: ['uthappam'] },
  'onion uttapam': { cal: 165, p: 4, c: 24, f: 5, fb: 2, score: 7, category: 'breakfast' },
  'tomato uttapam': { cal: 155, p: 4, c: 22, f: 5, fb: 2, score: 7, category: 'breakfast' },
  'mixed veg uttapam': { cal: 170, p: 5, c: 24, f: 6, fb: 3, score: 7, category: 'breakfast' },
  'medu vada': { cal: 130, p: 5, c: 14, f: 6, fb: 1, score: 5, category: 'breakfast', aliases: ['vada', 'urad vada'] },
  'sambar vada': { cal: 190, p: 7, c: 24, f: 7, fb: 3, score: 6, category: 'breakfast' },
  'dahi vada': { cal: 170, p: 6, c: 20, f: 7, fb: 2, score: 6, category: 'snack', aliases: ['curd vada'] },
  'masala vada': { cal: 120, p: 6, c: 14, f: 5, fb: 3, score: 6, category: 'snack', aliases: ['paruppu vada'] },
  'pongal': { cal: 180, p: 5, c: 26, f: 6, fb: 2, score: 7, category: 'breakfast', aliases: ['ven pongal'] },
  'upma': { cal: 165, p: 4, c: 26, f: 5, fb: 2, score: 7, category: 'breakfast' },
  'rava upma': { cal: 165, p: 4, c: 26, f: 5, fb: 2, score: 7, category: 'breakfast' },
  'vermicelli upma': { cal: 180, p: 4, c: 30, f: 5, fb: 1, score: 6, category: 'breakfast', aliases: ['semiya upma'] },
  'puttu': { cal: 190, p: 3, c: 32, f: 6, fb: 3, score: 7, category: 'breakfast' },
  'appam': { cal: 120, p: 2, c: 22, f: 2, fb: 1, score: 7, category: 'breakfast' },
  'egg appam': { cal: 200, p: 10, c: 22, f: 8, fb: 1, score: 7, category: 'breakfast' },
  'idiappam': { cal: 140, p: 3, c: 28, f: 1, fb: 1, score: 7, category: 'breakfast', aliases: ['string hoppers'] },
  'paniyaram': { cal: 120, p: 3, c: 18, f: 4, fb: 2, score: 7, category: 'breakfast', aliases: ['kuzhi paniyaram'] },
  'adai': { cal: 180, p: 8, c: 26, f: 5, fb: 4, score: 8, category: 'breakfast' },
  'dosai': { cal: 120, p: 3, c: 18, f: 4, fb: 1, score: 7, category: 'breakfast' },
  'kozhukattai': { cal: 130, p: 3, c: 22, f: 4, fb: 2, score: 7, category: 'snack', aliases: ['modak'] },
  'sambar': { cal: 90, p: 4, c: 14, f: 2, fb: 3, score: 8, category: 'side' },
  'rasam': { cal: 45, p: 2, c: 8, f: 1, fb: 1, score: 9, category: 'side', aliases: ['pepper rasam'] },
  'tomato rasam': { cal: 50, p: 2, c: 9, f: 1, fb: 1, score: 9, category: 'side' },
  'coconut chutney': { cal: 70, p: 1, c: 4, f: 6, fb: 2, score: 7, category: 'side' },
  'tomato chutney': { cal: 45, p: 1, c: 6, f: 2, fb: 1, score: 8, category: 'side' },
  'peanut chutney': { cal: 90, p: 4, c: 5, f: 7, fb: 2, score: 7, category: 'side' },
  'onion chutney': { cal: 50, p: 1, c: 6, f: 3, fb: 1, score: 7, category: 'side' },
  'avial': { cal: 160, p: 4, c: 12, f: 11, fb: 4, score: 8, category: 'side' },
  'kootu': { cal: 140, p: 6, c: 16, f: 5, fb: 4, score: 8, category: 'side' },
  'thoran': { cal: 100, p: 3, c: 8, f: 7, fb: 4, score: 8, category: 'side', aliases: ['poriyal'] },
  'kerala stew': { cal: 220, p: 5, c: 18, f: 14, fb: 3, score: 7, category: 'dinner' },
  'fish moilee': { cal: 280, p: 24, c: 8, f: 18, fb: 1, score: 7, category: 'dinner', aliases: ['meen moilee'] },
  'kerala fish curry': { cal: 300, p: 26, c: 10, f: 18, fb: 2, score: 7, category: 'dinner' },
  'meen pollichathu': { cal: 320, p: 28, c: 8, f: 20, fb: 1, score: 7, category: 'dinner' },
  'kesari': { cal: 220, p: 2, c: 38, f: 8, fb: 0, score: 3, category: 'dessert', aliases: ['rava kesari'] },
  'payasam': { cal: 250, p: 5, c: 40, f: 8, fb: 1, score: 4, category: 'dessert' },
  'ada pradhaman': { cal: 280, p: 4, c: 42, f: 10, fb: 1, score: 4, category: 'dessert' },
  'palada payasam': { cal: 260, p: 5, c: 38, f: 10, fb: 0, score: 4, category: 'dessert' },
  'filter coffee': { cal: 75, p: 2, c: 8, f: 3, fb: 0, score: 5, category: 'drink' },
  'degree coffee': { cal: 75, p: 2, c: 8, f: 3, fb: 0, score: 5, category: 'drink' },
  'mysore pak': { cal: 200, p: 3, c: 22, f: 12, fb: 1, score: 3, category: 'dessert' },
  'bisi bele bath': { cal: 270, p: 8, c: 42, f: 8, fb: 4, score: 7, category: 'lunch' },
  'vangi bath': { cal: 210, p: 5, c: 32, f: 7, fb: 3, score: 7, category: 'lunch', aliases: ['brinjal rice'] },
  'lemon rice': { cal: 190, p: 3, c: 32, f: 6, fb: 1, score: 7, category: 'lunch', aliases: ['chitranna'] },
  'tamarind rice': { cal: 200, p: 3, c: 34, f: 6, fb: 2, score: 6, category: 'lunch', aliases: ['puliyogare'] },
  'curd rice': { cal: 170, p: 5, c: 28, f: 4, fb: 1, score: 8, category: 'lunch', aliases: ['thayir sadam', 'mosaru anna'] },
  'tomato rice': { cal: 185, p: 3, c: 30, f: 6, fb: 2, score: 7, category: 'lunch' },
  'coconut rice': { cal: 210, p: 3, c: 30, f: 9, fb: 2, score: 6, category: 'lunch' },

  // ══════════════════════════════════════════════
  // NORTH INDIAN — Rotis, Curries, Dals
  // ══════════════════════════════════════════════
  'roti': { cal: 104, p: 3, c: 18, f: 3, fb: 2, score: 7, category: 'side', aliases: ['chapati', 'phulka'] },
  'paratha': { cal: 180, p: 4, c: 24, f: 8, fb: 2, score: 6, category: 'breakfast' },
  'aloo paratha': { cal: 200, p: 5, c: 28, f: 8, fb: 2, score: 5, category: 'breakfast' },
  'gobi paratha': { cal: 190, p: 5, c: 26, f: 8, fb: 3, score: 6, category: 'breakfast' },
  'paneer paratha': { cal: 240, p: 9, c: 26, f: 12, fb: 2, score: 6, category: 'breakfast' },
  'methi paratha': { cal: 180, p: 5, c: 24, f: 8, fb: 3, score: 7, category: 'breakfast' },
  'mooli paratha': { cal: 185, p: 4, c: 26, f: 8, fb: 3, score: 6, category: 'breakfast', aliases: ['radish paratha'] },
  'laccha paratha': { cal: 210, p: 4, c: 28, f: 10, fb: 2, score: 5, category: 'side' },
  'stuffed paratha': { cal: 220, p: 6, c: 28, f: 10, fb: 2, score: 6, category: 'breakfast' },
  'missi roti': { cal: 120, p: 5, c: 18, f: 3, fb: 3, score: 7, category: 'side' },
  'bajra roti': { cal: 110, p: 3, c: 20, f: 2, fb: 3, score: 8, category: 'side', aliases: ['bajre ki roti'] },
  'makki ki roti': { cal: 120, p: 3, c: 22, f: 2, fb: 3, score: 7, category: 'side' },
  'tandoori roti': { cal: 110, p: 3, c: 20, f: 2, fb: 2, score: 7, category: 'side' },
  'rumali roti': { cal: 100, p: 3, c: 18, f: 2, fb: 1, score: 6, category: 'side' },
  'naan': { cal: 260, p: 8, c: 42, f: 5, fb: 2, score: 5, category: 'side' },
  'butter naan': { cal: 300, p: 8, c: 42, f: 10, fb: 2, score: 4, category: 'side' },
  'garlic naan': { cal: 280, p: 8, c: 40, f: 8, fb: 2, score: 5, category: 'side' },
  'cheese naan': { cal: 330, p: 12, c: 38, f: 14, fb: 2, score: 4, category: 'side' },
  'peshawari naan': { cal: 310, p: 7, c: 44, f: 12, fb: 2, score: 4, category: 'side' },
  'kulcha': { cal: 220, p: 6, c: 34, f: 6, fb: 2, score: 5, category: 'side' },
  'amritsari kulcha': { cal: 260, p: 7, c: 36, f: 10, fb: 2, score: 5, category: 'side' },
  'bhatura': { cal: 240, p: 5, c: 32, f: 10, fb: 2, score: 3, category: 'side' },
  'puri': { cal: 120, p: 2, c: 14, f: 6, fb: 1, score: 4, category: 'side' },
  'dal': { cal: 150, p: 9, c: 22, f: 2, fb: 5, score: 9, category: 'lunch', aliases: ['plain dal'] },
  'dal tadka': { cal: 165, p: 9, c: 22, f: 4, fb: 5, score: 8, category: 'lunch' },
  'dal makhani': { cal: 230, p: 10, c: 26, f: 9, fb: 5, score: 7, category: 'dinner' },
  'dal fry': { cal: 155, p: 9, c: 22, f: 3, fb: 5, score: 8, category: 'lunch' },
  'chana dal': { cal: 160, p: 10, c: 24, f: 3, fb: 5, score: 8, category: 'side' },
  'moong dal': { cal: 140, p: 10, c: 20, f: 2, fb: 4, score: 9, category: 'side' },
  'masoor dal': { cal: 150, p: 11, c: 22, f: 1, fb: 5, score: 9, category: 'side' },
  'toor dal': { cal: 155, p: 10, c: 24, f: 2, fb: 5, score: 8, category: 'side' },
  'dal rice': { cal: 290, p: 12, c: 46, f: 5, fb: 6, score: 8, category: 'lunch' },
  'rajma': { cal: 180, p: 10, c: 30, f: 2, fb: 7, score: 8, category: 'lunch' },
  'rajma chawal': { cal: 320, p: 12, c: 52, f: 5, fb: 8, score: 7, category: 'lunch' },
  'chole': { cal: 220, p: 10, c: 32, f: 6, fb: 7, score: 7, category: 'lunch', aliases: ['chana masala', 'chickpea curry'] },
  'chole bhature': { cal: 430, p: 12, c: 50, f: 20, fb: 5, score: 4, category: 'lunch' },
  'chole kulche': { cal: 400, p: 12, c: 50, f: 16, fb: 5, score: 5, category: 'lunch' },
  'kadhi': { cal: 120, p: 4, c: 10, f: 7, fb: 2, score: 7, category: 'lunch', aliases: ['kadhi pakora'] },
  'kadhi chawal': { cal: 280, p: 8, c: 42, f: 9, fb: 3, score: 7, category: 'lunch' },
  'paneer': { cal: 265, p: 18, c: 4, f: 20, fb: 0, score: 6, category: 'side' },
  'paneer butter masala': { cal: 330, p: 14, c: 14, f: 24, fb: 2, score: 5, category: 'dinner' },
  'paneer tikka': { cal: 220, p: 14, c: 8, f: 14, fb: 2, score: 7, category: 'snack' },
  'paneer bhurji': { cal: 230, p: 14, c: 6, f: 16, fb: 2, score: 7, category: 'breakfast' },
  'paneer do pyaza': { cal: 260, p: 12, c: 12, f: 18, fb: 2, score: 6, category: 'dinner' },
  'shahi paneer': { cal: 310, p: 14, c: 12, f: 22, fb: 2, score: 5, category: 'dinner' },
  'palak paneer': { cal: 240, p: 14, c: 10, f: 16, fb: 4, score: 7, category: 'dinner' },
  'kadai paneer': { cal: 280, p: 14, c: 12, f: 20, fb: 3, score: 6, category: 'dinner' },
  'paneer tikka masala': { cal: 300, p: 14, c: 12, f: 20, fb: 2, score: 6, category: 'dinner' },
  'paneer lababdar': { cal: 290, p: 14, c: 12, f: 20, fb: 2, score: 5, category: 'dinner' },
  'matar paneer': { cal: 250, p: 12, c: 14, f: 16, fb: 4, score: 7, category: 'dinner' },
  'butter chicken': { cal: 250, p: 22, c: 8, f: 14, fb: 1, score: 5, category: 'dinner', aliases: ['murgh makhani'] },
  'chicken curry': { cal: 240, p: 22, c: 8, f: 14, fb: 2, score: 6, category: 'dinner' },
  'chicken korma': { cal: 300, p: 22, c: 10, f: 20, fb: 2, score: 5, category: 'dinner' },
  'chicken do pyaza': { cal: 250, p: 22, c: 10, f: 14, fb: 2, score: 6, category: 'dinner' },
  'chicken saag': { cal: 230, p: 22, c: 8, f: 12, fb: 3, score: 7, category: 'dinner' },
  'chicken keema': { cal: 220, p: 22, c: 4, f: 12, fb: 1, score: 7, category: 'dinner' },
  'chicken vindaloo': { cal: 260, p: 22, c: 8, f: 16, fb: 2, score: 6, category: 'dinner' },
  'kadai chicken': { cal: 250, p: 22, c: 10, f: 14, fb: 2, score: 6, category: 'dinner' },
  'mutton curry': { cal: 300, p: 24, c: 8, f: 20, fb: 1, score: 5, category: 'dinner', aliases: ['gosht curry'] },
  'mutton rogan josh': { cal: 290, p: 26, c: 6, f: 18, fb: 2, score: 6, category: 'dinner' },
  'mutton keema': { cal: 260, p: 22, c: 4, f: 16, fb: 1, score: 6, category: 'dinner' },
  'aloo gobi': { cal: 140, p: 3, c: 16, f: 7, fb: 3, score: 7, category: 'dinner' },
  'aloo matar': { cal: 150, p: 4, c: 18, f: 7, fb: 3, score: 7, category: 'dinner' },
  'aloo jeera': { cal: 130, p: 2, c: 16, f: 6, fb: 2, score: 6, category: 'side' },
  'aloo palak': { cal: 140, p: 3, c: 16, f: 7, fb: 3, score: 7, category: 'dinner' },
  'baingan bharta': { cal: 120, p: 3, c: 10, f: 8, fb: 4, score: 8, category: 'dinner', aliases: ['roasted eggplant'] },
  'bhindi masala': { cal: 110, p: 2, c: 10, f: 7, fb: 3, score: 7, category: 'dinner', aliases: ['okra fry'] },
  'palak dal': { cal: 190, p: 12, c: 24, f: 4, fb: 6, score: 9, category: 'dinner' },
  'lauki ki sabzi': { cal: 80, p: 2, c: 10, f: 4, fb: 2, score: 8, category: 'dinner', aliases: ['bottle gourd curry'] },
  'tinda masala': { cal: 85, p: 2, c: 8, f: 5, fb: 2, score: 7, category: 'dinner' },
  'mixed veg curry': { cal: 140, p: 4, c: 14, f: 8, fb: 4, score: 8, category: 'dinner' },
  'jeera rice': { cal: 160, p: 3, c: 30, f: 3, fb: 1, score: 6, category: 'side' },
  'raita': { cal: 60, p: 3, c: 4, f: 3, fb: 0, score: 8, category: 'side' },
  'boondi raita': { cal: 80, p: 3, c: 8, f: 4, fb: 0, score: 7, category: 'side' },
  'papad': { cal: 50, p: 3, c: 8, f: 1, fb: 1, score: 5, category: 'side', aliases: ['papadum'] },
  'pickle': { cal: 30, p: 0, c: 2, f: 2, fb: 1, score: 5, category: 'side', aliases: ['achar'] },

  // ══════════════════════════════════════════════
  // BIRYANI & RICE DISHES
  // ══════════════════════════════════════════════
  'rice': { cal: 130, p: 3, c: 28, f: 0, fb: 1, score: 6, category: 'side', aliases: ['plain rice', 'steamed rice', 'white rice'] },
  'brown rice': { cal: 140, p: 3, c: 30, f: 1, fb: 3, score: 8, category: 'side' },
  'biryani': { cal: 430, p: 25, c: 48, f: 16, fb: 2, score: 6, category: 'lunch', aliases: ['chicken biryani'] },
  'mutton biryani': { cal: 470, p: 24, c: 48, f: 20, fb: 2, score: 5, category: 'lunch' },
  'veg biryani': { cal: 310, p: 8, c: 46, f: 10, fb: 3, score: 7, category: 'lunch' },
  'egg biryani': { cal: 370, p: 16, c: 46, f: 14, fb: 2, score: 6, category: 'lunch' },
  'hyderabadi biryani': { cal: 450, p: 24, c: 48, f: 18, fb: 2, score: 6, category: 'lunch' },
  'lucknowi biryani': { cal: 420, p: 22, c: 48, f: 16, fb: 2, score: 6, category: 'lunch', aliases: ['awadhi biryani'] },
  'kolkata biryani': { cal: 400, p: 20, c: 48, f: 14, fb: 2, score: 6, category: 'lunch' },
  'ambur biryani': { cal: 440, p: 24, c: 46, f: 18, fb: 2, score: 6, category: 'lunch' },
  'dindigul biryani': { cal: 420, p: 22, c: 44, f: 18, fb: 2, score: 6, category: 'lunch' },
  'fish biryani': { cal: 370, p: 24, c: 44, f: 12, fb: 2, score: 7, category: 'lunch' },
  'prawn biryani': { cal: 380, p: 26, c: 44, f: 12, fb: 2, score: 7, category: 'lunch' },
  'vegetable pulao': { cal: 210, p: 5, c: 34, f: 6, fb: 3, score: 7, category: 'lunch', aliases: ['veg pulav'] },
  'peas pulao': { cal: 200, p: 5, c: 32, f: 5, fb: 3, score: 7, category: 'lunch', aliases: ['matar pulao'] },
  'ghee rice': { cal: 200, p: 3, c: 32, f: 7, fb: 1, score: 6, category: 'side' },
  'khichdi': { cal: 180, p: 6, c: 28, f: 4, fb: 3, score: 8, category: 'lunch', aliases: ['khichri'] },
  'dal khichdi': { cal: 200, p: 8, c: 30, f: 4, fb: 4, score: 8, category: 'lunch' },
  'moong dal khichdi': { cal: 190, p: 8, c: 28, f: 3, fb: 4, score: 9, category: 'lunch' },
  'fried rice': { cal: 260, p: 6, c: 38, f: 10, fb: 2, score: 5, category: 'lunch' },
  'veg fried rice': { cal: 250, p: 6, c: 36, f: 8, fb: 3, score: 5, category: 'lunch' },
  'egg fried rice': { cal: 290, p: 12, c: 38, f: 10, fb: 2, score: 5, category: 'lunch' },
  'chicken fried rice': { cal: 320, p: 16, c: 38, f: 12, fb: 2, score: 5, category: 'lunch' },
  'schezwan fried rice': { cal: 280, p: 6, c: 38, f: 12, fb: 2, score: 4, category: 'lunch' },

  // ══════════════════════════════════════════════
  // TANDOORI & MUGHLAI
  // ══════════════════════════════════════════════
  'tandoori chicken': { cal: 220, p: 28, c: 4, f: 10, fb: 1, score: 8, category: 'dinner' },
  'chicken tikka': { cal: 180, p: 24, c: 4, f: 8, fb: 1, score: 8, category: 'snack' },
  'malai tikka': { cal: 230, p: 22, c: 4, f: 14, fb: 1, score: 7, category: 'snack', aliases: ['malai chicken tikka'] },
  'reshmi kebab': { cal: 240, p: 26, c: 6, f: 12, fb: 1, score: 7, category: 'snack' },
  'seekh kebab': { cal: 260, p: 22, c: 8, f: 16, fb: 1, score: 6, category: 'snack' },
  'shami kebab': { cal: 180, p: 14, c: 10, f: 10, fb: 2, score: 7, category: 'snack' },
  'galouti kebab': { cal: 200, p: 14, c: 8, f: 12, fb: 1, score: 6, category: 'snack' },
  'chicken tikka masala': { cal: 280, p: 22, c: 10, f: 16, fb: 2, score: 6, category: 'dinner' },
  'haleem': { cal: 280, p: 16, c: 24, f: 12, fb: 4, score: 6, category: 'dinner' },
  'nihari': { cal: 320, p: 24, c: 8, f: 22, fb: 2, score: 5, category: 'dinner' },
  'tandoori fish': { cal: 220, p: 28, c: 4, f: 10, fb: 1, score: 8, category: 'dinner' },
  'tandoori paneer': { cal: 260, p: 16, c: 8, f: 18, fb: 2, score: 7, category: 'snack' },
  'tandoori prawns': { cal: 200, p: 24, c: 4, f: 10, fb: 0, score: 8, category: 'snack' },

  // ══════════════════════════════════════════════
  // STREET FOOD
  // ══════════════════════════════════════════════
  'samosa': { cal: 155, p: 3, c: 18, f: 8, fb: 1, score: 3, category: 'street-food' },
  'veg samosa': { cal: 155, p: 3, c: 18, f: 8, fb: 1, score: 3, category: 'street-food' },
  'chicken samosa': { cal: 190, p: 8, c: 18, f: 10, fb: 1, score: 4, category: 'street-food' },
  'vada pav': { cal: 290, p: 5, c: 38, f: 14, fb: 2, score: 3, category: 'street-food' },
  'pav bhaji': { cal: 310, p: 8, c: 40, f: 14, fb: 4, score: 5, category: 'street-food' },
  'pani puri': { cal: 140, p: 3, c: 22, f: 4, fb: 2, score: 4, category: 'street-food', aliases: ['gol gappa', 'puchka'] },
  'bhel puri': { cal: 160, p: 3, c: 24, f: 6, fb: 3, score: 5, category: 'street-food' },
  'sev puri': { cal: 170, p: 3, c: 22, f: 8, fb: 2, score: 4, category: 'street-food' },
  'dahi puri': { cal: 180, p: 4, c: 24, f: 8, fb: 2, score: 5, category: 'street-food' },
  'ragda pattice': { cal: 220, p: 6, c: 30, f: 8, fb: 4, score: 5, category: 'street-food' },
  'aloo tikki': { cal: 150, p: 3, c: 20, f: 7, fb: 2, score: 4, category: 'street-food' },
  'aloo tikki chaat': { cal: 220, p: 5, c: 28, f: 10, fb: 3, score: 5, category: 'street-food' },
  'papdi chaat': { cal: 190, p: 4, c: 24, f: 9, fb: 2, score: 4, category: 'street-food' },
  'kachori': { cal: 200, p: 4, c: 22, f: 11, fb: 2, score: 3, category: 'street-food' },
  'dabeli': { cal: 200, p: 4, c: 28, f: 8, fb: 3, score: 5, category: 'street-food' },
  'misal pav': { cal: 310, p: 12, c: 40, f: 12, fb: 5, score: 6, category: 'street-food' },
  'kathi roll': { cal: 280, p: 12, c: 26, f: 14, fb: 2, score: 5, category: 'street-food', aliases: ['frankie', 'wrap'] },
  'egg roll': { cal: 260, p: 12, c: 26, f: 12, fb: 2, score: 5, category: 'street-food' },
  'chicken roll': { cal: 300, p: 18, c: 26, f: 14, fb: 2, score: 5, category: 'street-food' },
  'veg momos': { cal: 160, p: 5, c: 22, f: 6, fb: 2, score: 6, category: 'street-food' },
  'chicken momos': { cal: 200, p: 12, c: 22, f: 8, fb: 1, score: 6, category: 'street-food' },
  'fried momos': { cal: 260, p: 8, c: 26, f: 14, fb: 1, score: 3, category: 'street-food' },
  'shawarma': { cal: 320, p: 18, c: 32, f: 14, fb: 2, score: 5, category: 'street-food' },
  'masala corn': { cal: 160, p: 4, c: 28, f: 4, fb: 4, score: 7, category: 'street-food' },
  'bhutta': { cal: 140, p: 4, c: 26, f: 3, fb: 3, score: 7, category: 'street-food', aliases: ['roasted corn'] },
  'chana jor garam': { cal: 180, p: 10, c: 26, f: 4, fb: 5, score: 7, category: 'street-food' },
  'chole tikki': { cal: 260, p: 8, c: 34, f: 10, fb: 4, score: 5, category: 'street-food' },
  'bread pakora': { cal: 190, p: 5, c: 22, f: 10, fb: 1, score: 3, category: 'street-food' },
  'onion pakora': { cal: 140, p: 3, c: 14, f: 8, fb: 2, score: 4, category: 'street-food', aliases: ['pyaz pakoda', 'onion bhaji'] },
  'palak pakora': { cal: 120, p: 3, c: 12, f: 7, fb: 2, score: 5, category: 'street-food' },
  'mirchi bajji': { cal: 130, p: 2, c: 14, f: 7, fb: 2, score: 4, category: 'street-food', aliases: ['mirchi pakoda'] },
  'gobi pakora': { cal: 135, p: 3, c: 14, f: 8, fb: 2, score: 4, category: 'street-food' },

  // ══════════════════════════════════════════════
  // BENGALI & EASTERN
  // ══════════════════════════════════════════════
  'fish curry': { cal: 230, p: 22, c: 8, f: 12, fb: 2, score: 7, category: 'dinner', aliases: ['machher jhol'] },
  'hilsa curry': { cal: 280, p: 20, c: 6, f: 20, fb: 1, score: 6, category: 'dinner', aliases: ['ilish bhapa'] },
  'chingri malai curry': { cal: 260, p: 18, c: 8, f: 18, fb: 1, score: 6, category: 'dinner', aliases: ['prawn malai curry'] },
  'kosha mangsho': { cal: 310, p: 24, c: 6, f: 22, fb: 2, score: 5, category: 'dinner' },
  'luchi': { cal: 140, p: 3, c: 18, f: 6, fb: 1, score: 4, category: 'breakfast' },
  'shukto': { cal: 120, p: 4, c: 14, f: 6, fb: 4, score: 8, category: 'side' },
  'aloo posto': { cal: 180, p: 4, c: 20, f: 10, fb: 3, score: 6, category: 'side' },
  'mishti doi': { cal: 180, p: 5, c: 28, f: 5, fb: 0, score: 5, category: 'dessert' },
  'doi maach': { cal: 300, p: 24, c: 10, f: 18, fb: 1, score: 6, category: 'dinner' },
  'begun bhaja': { cal: 120, p: 2, c: 10, f: 8, fb: 3, score: 5, category: 'side' },
  'litti chokha': { cal: 280, p: 8, c: 42, f: 10, fb: 4, score: 7, category: 'lunch' },
  'sattu paratha': { cal: 230, p: 10, c: 30, f: 9, fb: 4, score: 7, category: 'breakfast' },

  // ══════════════════════════════════════════════
  // WESTERN INDIAN (GUJARATI + MAHARASHTRIAN)
  // ══════════════════════════════════════════════
  'dhokla': { cal: 160, p: 6, c: 24, f: 4, fb: 2, score: 8, category: 'snack' },
  'khandvi': { cal: 140, p: 6, c: 18, f: 5, fb: 1, score: 8, category: 'snack' },
  'thepla': { cal: 180, p: 5, c: 24, f: 7, fb: 3, score: 7, category: 'breakfast' },
  'fafda': { cal: 220, p: 5, c: 26, f: 11, fb: 2, score: 4, category: 'breakfast' },
  'undhiyu': { cal: 280, p: 8, c: 28, f: 16, fb: 6, score: 7, category: 'lunch' },
  'shrikhand': { cal: 200, p: 5, c: 30, f: 7, fb: 0, score: 5, category: 'dessert' },
  'handvo': { cal: 220, p: 8, c: 30, f: 8, fb: 3, score: 7, category: 'snack' },
  'khaman': { cal: 180, p: 7, c: 26, f: 5, fb: 2, score: 7, category: 'snack' },
  'gathiya': { cal: 260, p: 6, c: 28, f: 14, fb: 2, score: 4, category: 'snack' },
  'dal dhokli': { cal: 320, p: 12, c: 44, f: 10, fb: 5, score: 7, category: 'lunch' },
  'gujarati kadhi': { cal: 140, p: 4, c: 12, f: 8, fb: 1, score: 7, category: 'side' },
  'puran poli': { cal: 280, p: 6, c: 44, f: 8, fb: 3, score: 5, category: 'dessert' },
  'thalipeeth': { cal: 200, p: 7, c: 28, f: 7, fb: 4, score: 7, category: 'breakfast' },
  'sabudana khichdi': { cal: 200, p: 3, c: 34, f: 7, fb: 2, score: 5, category: 'breakfast' },
  'poha': { cal: 180, p: 4, c: 30, f: 5, fb: 2, score: 7, category: 'breakfast', aliases: ['kanda poha'] },
  'batata poha': { cal: 195, p: 3, c: 32, f: 6, fb: 2, score: 6, category: 'breakfast' },
  'bharli vangi': { cal: 180, p: 4, c: 14, f: 12, fb: 4, score: 7, category: 'side' },
  'usal': { cal: 200, p: 12, c: 28, f: 4, fb: 6, score: 8, category: 'side' },
  'pithla bhakri': { cal: 220, p: 8, c: 30, f: 7, fb: 4, score: 7, category: 'lunch' },
  'zunka bhakri': { cal: 210, p: 8, c: 30, f: 6, fb: 4, score: 7, category: 'lunch' },
  'varan bhaat': { cal: 280, p: 10, c: 44, f: 5, fb: 5, score: 8, category: 'lunch' },

  // ══════════════════════════════════════════════
  // DRINKS
  // ══════════════════════════════════════════════
  'chai': { cal: 60, p: 2, c: 8, f: 2, fb: 0, score: 5, category: 'drink', aliases: ['tea'] },
  'masala chai': { cal: 70, p: 2, c: 10, f: 2, fb: 0, score: 5, category: 'drink' },
  'green tea': { cal: 5, p: 0, c: 1, f: 0, fb: 0, score: 9, category: 'drink' },
  'black tea': { cal: 5, p: 0, c: 1, f: 0, fb: 0, score: 8, category: 'drink' },
  'black coffee': { cal: 5, p: 0, c: 1, f: 0, fb: 0, score: 8, category: 'drink' },
  'cold coffee': { cal: 150, p: 3, c: 24, f: 5, fb: 0, score: 4, category: 'drink' },
  'lassi': { cal: 130, p: 4, c: 20, f: 4, fb: 0, score: 6, category: 'drink' },
  'sweet lassi': { cal: 150, p: 4, c: 24, f: 4, fb: 0, score: 5, category: 'drink' },
  'salted lassi': { cal: 80, p: 4, c: 8, f: 3, fb: 0, score: 7, category: 'drink' },
  'mango lassi': { cal: 170, p: 4, c: 28, f: 4, fb: 1, score: 5, category: 'drink' },
  'chaas': { cal: 40, p: 2, c: 4, f: 2, fb: 0, score: 8, category: 'drink', aliases: ['buttermilk', 'mattha'] },
  'nimbu pani': { cal: 40, p: 0, c: 10, f: 0, fb: 0, score: 8, category: 'drink', aliases: ['lime water', 'shikanji'] },
  'aam panna': { cal: 60, p: 0, c: 14, f: 0, fb: 1, score: 8, category: 'drink' },
  'jaljeera': { cal: 30, p: 0, c: 6, f: 0, fb: 0, score: 8, category: 'drink' },
  'thandai': { cal: 160, p: 5, c: 20, f: 7, fb: 2, score: 6, category: 'drink' },
  'badam milk': { cal: 150, p: 5, c: 18, f: 7, fb: 1, score: 7, category: 'drink', aliases: ['almond milk'] },
  'haldi doodh': { cal: 100, p: 4, c: 12, f: 4, fb: 0, score: 8, category: 'drink', aliases: ['turmeric milk', 'golden milk'] },
  'masala milk': { cal: 120, p: 4, c: 14, f: 5, fb: 0, score: 7, category: 'drink' },
  'coconut water': { cal: 46, p: 0, c: 9, f: 0, fb: 0, score: 9, category: 'drink', aliases: ['nariyal pani', 'tender coconut'] },
  'sugarcane juice': { cal: 100, p: 0, c: 25, f: 0, fb: 0, score: 6, category: 'drink', aliases: ['ganne ka ras'] },
  'mango shake': { cal: 180, p: 4, c: 32, f: 5, fb: 1, score: 5, category: 'drink' },
  'banana shake': { cal: 170, p: 5, c: 28, f: 4, fb: 2, score: 6, category: 'drink' },
  'watermelon juice': { cal: 60, p: 1, c: 14, f: 0, fb: 1, score: 8, category: 'drink' },
  'orange juice': { cal: 110, p: 2, c: 26, f: 0, fb: 0, score: 7, category: 'drink' },
  'pomegranate juice': { cal: 130, p: 1, c: 32, f: 0, fb: 0, score: 8, category: 'drink' },
  'protein shake': { cal: 280, p: 30, c: 20, f: 8, fb: 2, score: 7, category: 'drink' },
  'water': { cal: 0, p: 0, c: 0, f: 0, fb: 0, score: 10, category: 'drink' },
  'soda': { cal: 140, p: 0, c: 36, f: 0, fb: 0, score: 1, category: 'drink', aliases: ['soft drink', 'cola', 'coke', 'pepsi'] },
  'beer': { cal: 150, p: 1, c: 13, f: 0, fb: 0, score: 2, category: 'drink' },

  // ══════════════════════════════════════════════
  // DESSERTS & SWEETS
  // ══════════════════════════════════════════════
  'gulab jamun': { cal: 150, p: 2, c: 26, f: 5, fb: 0, score: 2, category: 'dessert' },
  'jalebi': { cal: 150, p: 1, c: 28, f: 5, fb: 0, score: 2, category: 'dessert' },
  'rasgulla': { cal: 125, p: 3, c: 22, f: 2, fb: 0, score: 3, category: 'dessert' },
  'sandesh': { cal: 140, p: 4, c: 22, f: 4, fb: 0, score: 4, category: 'dessert' },
  'chom chom': { cal: 160, p: 4, c: 26, f: 5, fb: 0, score: 3, category: 'dessert' },
  'rasmalai': { cal: 180, p: 5, c: 28, f: 6, fb: 0, score: 3, category: 'dessert' },
  'kheer': { cal: 200, p: 5, c: 32, f: 6, fb: 0, score: 4, category: 'dessert', aliases: ['rice kheer'] },
  'phirni': { cal: 180, p: 4, c: 28, f: 6, fb: 0, score: 4, category: 'dessert' },
  'rabdi': { cal: 220, p: 5, c: 30, f: 10, fb: 0, score: 3, category: 'dessert', aliases: ['rabri'] },
  'kulfi': { cal: 190, p: 4, c: 24, f: 8, fb: 0, score: 4, category: 'dessert' },
  'malpua': { cal: 250, p: 4, c: 36, f: 10, fb: 1, score: 3, category: 'dessert' },
  'basundi': { cal: 200, p: 5, c: 28, f: 8, fb: 0, score: 4, category: 'dessert' },
  'gajar halwa': { cal: 230, p: 4, c: 32, f: 10, fb: 2, score: 4, category: 'dessert', aliases: ['carrot halwa'] },
  'moong dal halwa': { cal: 220, p: 5, c: 28, f: 10, fb: 2, score: 4, category: 'dessert' },
  'suji halwa': { cal: 200, p: 3, c: 30, f: 8, fb: 1, score: 3, category: 'dessert', aliases: ['sooji halwa'] },
  'besan ladoo': { cal: 120, p: 3, c: 14, f: 6, fb: 1, score: 4, category: 'dessert' },
  'motichoor ladoo': { cal: 130, p: 2, c: 18, f: 6, fb: 0, score: 3, category: 'dessert' },
  'boondi ladoo': { cal: 140, p: 2, c: 20, f: 6, fb: 0, score: 3, category: 'dessert' },
  'coconut ladoo': { cal: 100, p: 1, c: 12, f: 6, fb: 2, score: 4, category: 'dessert', aliases: ['nariyal ladoo'] },
  'kaju katli': { cal: 120, p: 3, c: 14, f: 6, fb: 0, score: 4, category: 'dessert', aliases: ['kaju barfi'] },
  'barfi': { cal: 130, p: 3, c: 16, f: 6, fb: 0, score: 3, category: 'dessert', aliases: ['burfi'] },
  'peda': { cal: 100, p: 3, c: 14, f: 4, fb: 0, score: 4, category: 'dessert' },
  'soan papdi': { cal: 110, p: 2, c: 16, f: 5, fb: 0, score: 3, category: 'dessert' },
  'gajak': { cal: 140, p: 3, c: 16, f: 8, fb: 1, score: 4, category: 'dessert' },
  'imarti': { cal: 160, p: 2, c: 26, f: 6, fb: 0, score: 2, category: 'dessert' },
  'ice cream': { cal: 200, p: 3, c: 24, f: 10, fb: 0, score: 3, category: 'dessert' },

  // ══════════════════════════════════════════════
  // INDO-CHINESE & FAST FOOD
  // ══════════════════════════════════════════════
  'manchurian': { cal: 220, p: 5, c: 22, f: 12, fb: 2, score: 4, category: 'snack', aliases: ['veg manchurian'] },
  'gobi manchurian': { cal: 200, p: 4, c: 20, f: 12, fb: 2, score: 4, category: 'snack' },
  'chicken manchurian': { cal: 260, p: 16, c: 20, f: 14, fb: 1, score: 4, category: 'dinner' },
  'chilli paneer': { cal: 250, p: 12, c: 14, f: 16, fb: 2, score: 5, category: 'snack' },
  'chilli chicken': { cal: 260, p: 20, c: 14, f: 14, fb: 1, score: 5, category: 'snack' },
  'chilli gobi': { cal: 190, p: 4, c: 18, f: 12, fb: 2, score: 4, category: 'snack' },
  'baby corn chilli': { cal: 220, p: 4, c: 22, f: 12, fb: 2, score: 5, category: 'snack' },
  'spring roll': { cal: 180, p: 4, c: 22, f: 8, fb: 2, score: 4, category: 'snack' },
  'hakka noodles': { cal: 340, p: 8, c: 48, f: 14, fb: 2, score: 4, category: 'lunch' },
  'veg noodles': { cal: 320, p: 7, c: 46, f: 12, fb: 3, score: 4, category: 'lunch' },
  'chicken noodles': { cal: 380, p: 16, c: 46, f: 14, fb: 2, score: 4, category: 'lunch' },
  'schezwan noodles': { cal: 360, p: 8, c: 48, f: 14, fb: 2, score: 3, category: 'lunch' },
  'maggi': { cal: 310, p: 7, c: 42, f: 13, fb: 1, score: 3, category: 'snack', aliases: ['instant noodles'] },
  'pizza': { cal: 680, p: 28, c: 72, f: 30, fb: 3, score: 3, category: 'dinner' },
  'pizza slice': { cal: 280, p: 12, c: 30, f: 12, fb: 1, score: 3, category: 'snack' },
  'burger': { cal: 550, p: 25, c: 45, f: 28, fb: 2, score: 3, category: 'lunch' },
  'veg burger': { cal: 420, p: 12, c: 48, f: 18, fb: 3, score: 4, category: 'lunch' },
  'chicken burger': { cal: 520, p: 24, c: 42, f: 26, fb: 2, score: 3, category: 'lunch' },
  'pasta': { cal: 450, p: 15, c: 58, f: 16, fb: 3, score: 5, category: 'dinner' },
  'white sauce pasta': { cal: 480, p: 14, c: 56, f: 22, fb: 2, score: 4, category: 'dinner' },
  'red sauce pasta': { cal: 420, p: 14, c: 58, f: 14, fb: 3, score: 5, category: 'dinner' },
  'sandwich': { cal: 320, p: 14, c: 36, f: 14, fb: 3, score: 6, category: 'snack' },
  'veg sandwich': { cal: 280, p: 8, c: 34, f: 12, fb: 3, score: 6, category: 'snack' },
  'grilled sandwich': { cal: 340, p: 12, c: 36, f: 16, fb: 2, score: 5, category: 'snack' },
  'paneer wrap': { cal: 380, p: 16, c: 34, f: 18, fb: 2, score: 5, category: 'lunch' },
  'chicken wrap': { cal: 400, p: 22, c: 34, f: 18, fb: 2, score: 5, category: 'lunch' },
  'french fries': { cal: 320, p: 4, c: 40, f: 16, fb: 3, score: 2, category: 'snack' },
  'soup': { cal: 80, p: 3, c: 10, f: 3, fb: 2, score: 7, category: 'side' },
  'tomato soup': { cal: 90, p: 2, c: 14, f: 3, fb: 2, score: 7, category: 'side' },
  'sweet corn soup': { cal: 100, p: 3, c: 16, f: 3, fb: 2, score: 7, category: 'side' },
  'hot and sour soup': { cal: 80, p: 4, c: 10, f: 2, fb: 1, score: 6, category: 'side' },
  'manchow soup': { cal: 120, p: 4, c: 14, f: 5, fb: 1, score: 5, category: 'side' },

  // ══════════════════════════════════════════════
  // EGGS
  // ══════════════════════════════════════════════
  'boiled egg': { cal: 78, p: 6, c: 1, f: 5, fb: 0, score: 9, category: 'breakfast', aliases: ['hard boiled egg'] },
  'eggs': { cal: 155, p: 13, c: 1, f: 11, fb: 0, score: 8, category: 'breakfast', aliases: ['2 eggs'] },
  'omelette': { cal: 180, p: 14, c: 2, f: 13, fb: 0, score: 8, category: 'breakfast' },
  'masala omelette': { cal: 200, p: 14, c: 4, f: 14, fb: 1, score: 7, category: 'breakfast' },
  'egg bhurji': { cal: 220, p: 14, c: 4, f: 16, fb: 1, score: 7, category: 'breakfast' },
  'egg curry': { cal: 280, p: 18, c: 12, f: 18, fb: 2, score: 7, category: 'dinner' },
  'anda masala': { cal: 280, p: 18, c: 12, f: 18, fb: 2, score: 7, category: 'dinner' },
  'egg paratha': { cal: 340, p: 14, c: 36, f: 16, fb: 2, score: 6, category: 'breakfast' },

  // ══════════════════════════════════════════════
  // HEALTHY & MODERN
  // ══════════════════════════════════════════════
  'oats': { cal: 180, p: 6, c: 28, f: 4, fb: 4, score: 8, category: 'breakfast', aliases: ['oatmeal', 'porridge'] },
  'masala oats': { cal: 200, p: 7, c: 30, f: 5, fb: 4, score: 7, category: 'breakfast' },
  'overnight oats': { cal: 240, p: 8, c: 34, f: 8, fb: 4, score: 8, category: 'breakfast' },
  'muesli': { cal: 280, p: 8, c: 42, f: 8, fb: 5, score: 7, category: 'breakfast' },
  'granola': { cal: 300, p: 7, c: 40, f: 12, fb: 4, score: 6, category: 'breakfast' },
  'smoothie bowl': { cal: 280, p: 8, c: 40, f: 10, fb: 5, score: 8, category: 'breakfast' },
  'quinoa': { cal: 220, p: 8, c: 36, f: 4, fb: 3, score: 9, category: 'lunch' },
  'quinoa salad': { cal: 250, p: 10, c: 34, f: 8, fb: 5, score: 9, category: 'lunch' },
  'salad': { cal: 180, p: 8, c: 14, f: 10, fb: 6, score: 9, category: 'lunch' },
  'fruit salad': { cal: 120, p: 1, c: 30, f: 0, fb: 4, score: 9, category: 'snack' },
  'sprouts': { cal: 100, p: 8, c: 14, f: 1, fb: 4, score: 9, category: 'snack', aliases: ['sprouted moong'] },
  'sprouts salad': { cal: 130, p: 8, c: 18, f: 2, fb: 5, score: 9, category: 'snack' },
  'multigrain roti': { cal: 130, p: 5, c: 20, f: 3, fb: 4, score: 8, category: 'side' },
  'grilled chicken': { cal: 220, p: 32, c: 2, f: 8, fb: 0, score: 9, category: 'dinner' },
  'grilled fish': { cal: 200, p: 28, c: 2, f: 8, fb: 0, score: 9, category: 'dinner' },
  'grilled paneer': { cal: 240, p: 16, c: 4, f: 18, fb: 1, score: 7, category: 'snack' },
  'steamed fish': { cal: 160, p: 28, c: 1, f: 4, fb: 0, score: 9, category: 'dinner' },
  'protein bar': { cal: 200, p: 20, c: 22, f: 6, fb: 3, score: 7, category: 'snack' },
  'peanut butter toast': { cal: 280, p: 10, c: 28, f: 14, fb: 3, score: 7, category: 'breakfast' },
  'avocado toast': { cal: 260, p: 6, c: 24, f: 16, fb: 6, score: 8, category: 'breakfast' },
  'greek yogurt': { cal: 100, p: 10, c: 6, f: 4, fb: 0, score: 9, category: 'snack' },

  // ══════════════════════════════════════════════
  // FRUITS & BASICS
  // ══════════════════════════════════════════════
  'banana': { cal: 105, p: 1, c: 27, f: 0, fb: 3, score: 7, category: 'snack' },
  'apple': { cal: 95, p: 0, c: 25, f: 0, fb: 4, score: 8, category: 'snack' },
  'mango': { cal: 135, p: 1, c: 35, f: 0, fb: 3, score: 7, category: 'snack' },
  'orange': { cal: 62, p: 1, c: 15, f: 0, fb: 3, score: 8, category: 'snack' },
  'papaya': { cal: 60, p: 1, c: 14, f: 0, fb: 3, score: 8, category: 'snack' },
  'watermelon': { cal: 46, p: 1, c: 12, f: 0, fb: 1, score: 8, category: 'snack' },
  'pomegranate': { cal: 105, p: 2, c: 26, f: 0, fb: 4, score: 9, category: 'snack' },
  'guava': { cal: 68, p: 2, c: 14, f: 1, fb: 5, score: 9, category: 'snack' },
  'grapes': { cal: 70, p: 1, c: 18, f: 0, fb: 1, score: 7, category: 'snack' },
  'pineapple': { cal: 80, p: 1, c: 20, f: 0, fb: 2, score: 7, category: 'snack' },
  'chikoo': { cal: 100, p: 1, c: 24, f: 1, fb: 3, score: 6, category: 'snack', aliases: ['sapota'] },
  'bread toast': { cal: 140, p: 4, c: 24, f: 3, fb: 1, score: 5, category: 'breakfast', aliases: ['toast'] },
  'bread butter': { cal: 180, p: 4, c: 24, f: 8, fb: 1, score: 4, category: 'breakfast' },
  'jam toast': { cal: 170, p: 3, c: 30, f: 3, fb: 1, score: 4, category: 'breakfast' },
  'cornflakes': { cal: 200, p: 4, c: 36, f: 4, fb: 1, score: 5, category: 'breakfast', aliases: ['cereal'] },
  'curd': { cal: 60, p: 4, c: 5, f: 3, fb: 0, score: 8, category: 'side', aliases: ['yogurt', 'dahi'] },
  'paneer paratha with curd': { cal: 400, p: 16, c: 38, f: 21, fb: 2, score: 6, category: 'breakfast' },
  'roti sabzi': { cal: 310, p: 10, c: 42, f: 12, fb: 5, score: 7, category: 'dinner' },
  'thali': { cal: 650, p: 20, c: 80, f: 28, fb: 8, score: 7, category: 'lunch', aliases: ['veg thali'] },
  'non veg thali': { cal: 780, p: 32, c: 82, f: 34, fb: 6, score: 6, category: 'lunch' },
  'meals': { cal: 600, p: 16, c: 78, f: 22, fb: 6, score: 7, category: 'lunch', aliases: ['south indian meals'] },
};
